language: android
jdk:
- openjdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-26
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_c84f371e8e95_key -iv $encrypted_c84f371e8e95_iv
  -in publish.keystore.enc -out app/publish.keystore -d
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: fb256dfe5d20e5e96d118c46356801fb6797d04c
  file: app/build/outputs/apk/app-releases.apk
  skip_cleanup: true
